vim.cmd("set expandtab")
vim.cmd("set tabstop=2")
vim.cmd("set softtabstop=2")
vim.cmd("set shiftwidth=2")
vim.cmd("set number")
vim.g.mapleader = " "
vim.cmd("filetype indent on")
vim.cmd("set number")
vim.cmd("set relativenumber")
vim.cmd("set guicursor=i:block")
vim.cmd("lua vim.diagnostic.open_float()")
vim.keymap.set("i", "C-c", "<Esc>")
